/**
 * Index file that explicitly imports all pattern JSON files
 * This ensures Vite can discover and bundle them properly
 * 
 * Pattern files will be generated by star-battle-patterns/ and placed here
 */

// TODO: Import pattern files once they are generated
// Example:
// import patternsA1 from './10x10-A1_rowBand_regionBudget-patterns.json';
// import patternsC2 from './10x10-C2_cages_regionQuota-patterns.json';

export const patternFiles: Array<{ id: string; data: any }> = [
  // Pattern files will be added here when generated
];

