/**
 * Index file that explicitly imports all pattern JSON files
 * This ensures Vite can discover and bundle them properly
 * 
 * Pattern files will be generated by star-battle-patterns/ and placed here
 */

import patternsA1_rowBand from './10x10-A1_rowBand_regionBudget-patterns.json';
import patternsA1_rowBandRegion from './10x10-A1_rowBandRegionBudget-patterns.json';
import patternsA2_colBand from './10x10-A2_colBand_regionBudget-patterns.json';
import patternsA2_colBandRegion from './10x10-A2_colBandRegionBudget-patterns.json';
import patternsA3 from './10x10-A3_regionRowBandPartition-patterns.json';
import patternsA4 from './10x10-A4_regionColBandPartition-patterns.json';
import patternsB1 from './10x10-B1_exclusiveRegionsRowBand-patterns.json';
import patternsB2 from './10x10-B2_exclusiveRegionsColBand-patterns.json';
import patternsB3 from './10x10-B3_exclusiveRowsInRegion-patterns.json';
import patternsB4 from './10x10-B4_exclusiveColsInRegion-patterns.json';
import patternsC1 from './10x10-C1_bandExactCages-patterns.json';
import patternsC2_cages from './10x10-C2_cages_regionQuota-patterns.json';
import patternsC2_cagesRegion from './10x10-C2_cagesRegionQuota-patterns.json';
import patternsC3 from './10x10-C3_internalCagePlacement-patterns.json';
import patternsC4 from './10x10-C4_cageExclusion-patterns.json';
import patternsD1 from './10x10-D1_rowColIntersection-patterns.json';
import patternsD2 from './10x10-D2_regionBandIntersection-patterns.json';
import patternsE1 from './10x10-E1_candidateDeficit-patterns.json';
import patternsE2 from './10x10-E2_partitionedCandidates-patterns.json';
import patternsF1 from './10x10-F1_regionPairExclusion-patterns.json';
import patternsF2 from './10x10-F2_exclusivityChains-patterns.json';

export const patternFiles: Array<{ id: string; data: any }> = [
  { id: patternsA1_rowBand.family_id, data: patternsA1_rowBand },
  { id: patternsA1_rowBandRegion.family_id, data: patternsA1_rowBandRegion },
  { id: patternsA2_colBand.family_id, data: patternsA2_colBand },
  { id: patternsA2_colBandRegion.family_id, data: patternsA2_colBandRegion },
  { id: patternsA3.family_id, data: patternsA3 },
  { id: patternsA4.family_id, data: patternsA4 },
  { id: patternsB1.family_id, data: patternsB1 },
  { id: patternsB2.family_id, data: patternsB2 },
  { id: patternsB3.family_id, data: patternsB3 },
  { id: patternsB4.family_id, data: patternsB4 },
  { id: patternsC1.family_id, data: patternsC1 },
  { id: patternsC2_cages.family_id, data: patternsC2_cages },
  { id: patternsC2_cagesRegion.family_id, data: patternsC2_cagesRegion },
  { id: patternsC3.family_id, data: patternsC3 },
  { id: patternsC4.family_id, data: patternsC4 },
  { id: patternsD1.family_id, data: patternsD1 },
  { id: patternsD2.family_id, data: patternsD2 },
  { id: patternsE1.family_id, data: patternsE1 },
  { id: patternsE2.family_id, data: patternsE2 },
  { id: patternsF1.family_id, data: patternsF1 },
  { id: patternsF2.family_id, data: patternsF2 },
];

